### ISSUE TITLE
Investigate auto creating usable JAR on CI

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3203]
### Desired behaviour
Dockstore-UI2 needs an up-to-date jar for tests.  Currently we only have that upon new webservice release.  One way to is build the JAR on CircleCI and upload as an artifact.  Sample code:
```
      - run:
          name: Make jar directory
          command: mkdir /tmp/artifacts
      - run:
          name: Move jars
          command: cp dockstore-webservice/target/dockstore*.jar /tmp/artifacts
      - run:
          name: Move swagger.yaml
          command: |
            cp dockstore-webservice/src/main/resources/swagger.yaml /tmp/artifacts
            cp dockstore-webservice/src/main/resources/openapi3/openapi.yaml /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
```
Things to note:
- The URL is not intuitive. https://2602-33383826-gh.circle-artifacts.com/0/tmp/artifacts/dockstore-webservice-1.8.0-alpha.3-SNAPSHOT.jar
- The URL should mention the release somewhere
- It should only be built and uploaded when merged to develop.

Additionally, this issue may be deprecated upon new CI/CD work

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1197)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-1197
┆Sprint: Backlog
┆Issue Type: Story
