### ISSUE TITLE
ImageType Enum Mismatch

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3284]
**Describe the bug**
TRS schema expects ImageType to be enum of:
```
  ImageType:
    type: string
    description: Indicates what kind of container is this image is.
    enum:
      - Docker
      - Singularity
      - Conda
```
Our TRS on dev.dockstore.net returns something like "DOCKER" instead

**To Reproduce**
1. Go to http://142.1.177.188:8080/trs/validator/debug?url=https://dev.dockstore.net/api
See that it complains about ImageType

**Expected behavior**
TRSV should not complain about ImageType

**Additional context**
 - host location: dev.dockstore.net

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1245)
┆Issue Type: Story
┆Sprint: Sprint 30 Eel
┆Issue Number: DOCK-1245
