### ISSUE TITLE
Misleading message for workflows coming back via lambda logs

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3564]
**Describe the bug**
Error message claims that the needed property is "workflow" when it should be "workflows"

**To Reproduce**
Register a .dockstore.yml using "workflow" rather than "workflows" as a key
Look in lambda logs

**Expected behavior**
Term should be workflows

**Screenshots**

Use 
```
version: 1.2
workflow:
   - subclass: NFL
     primaryDescriptorPath: /nextflow.config
```
(which is wrong)

![Screenshot from 2020-06-12 11-39-35](https://user-images.githubusercontent.com/1730679/84520575-c438f280-aca1-11ea-8e28-2dc63b4f2fac.png)

**Additional context**
dev.dockstore.org

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-1418)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.10
┆Sprint: Backlog
┆Issue Number: DOCK-1418
