### ISSUE TITLE
Dockstore CLI generates invalid JSON if Dockstore CLI wants you to update

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4048]
**Describe the bug**
Due to the nature of this bug I can't be sure if it still exists in 1.10.0, but it does exist in 1.9.0 so it might be worth looking into. Basically, when using Dockstore's recommended method for generating a JSON for a WDL, the output WDL will include error output about Dockstore's version being out of date, resulting in an invalid WDL.

**To Reproduce**
1. Be using Dockstore 1.9.0
2. Run `dockstore workflow convert entry2json --entry github.com/manning-lab/vcfToGds:master > Dockstore.json`
3. End up with a Dockstore.json that looks like this

> 14:23:17.596 [main] ERROR io.dockstore.client.cli.ArgumentUtility - Current version : 1.9.0
> 14:23:17.599 [main] ERROR io.dockstore.client.cli.ArgumentUtility - Latest version : 1.10.0
> 14:23:17.599 [main] ERROR io.dockstore.client.cli.ArgumentUtility - You do not have the most recent stable release of Dockstore.
> Please upgrade with the following command:
>    dockstore --upgrade
> {
>   "vcfToGds_wf.vcf_files": "Array[File]",
>   "vcfToGds_wf.this_disk": "Int",
>   "vcfToGds_wf.this_memory": "Float"
> }

**Expected behavior**
The error output should not be in the output file. The resulting JSON should be valid.

**Screenshots**
<img width="1143" alt="Screenshot 2021-02-16 at 2 29 45 PM" src="https://user-images.githubusercontent.com/27784612/108129926-af4c0480-7063-11eb-87a3-b49dd7da6be0.png">

**Desktop (please complete the following information):**
 - OS: Catalina
 - Version: Dockstore CLI 1.9.0 but may persist in 1.10.0

**Comment by denis-yuen** [comment]
Looks like https://github.com/dockstore/dockstore/issues/3426#issuecomment-623713391

**Comment by aofarrel** [comment]
Seems to be a consequence of that, yep. I'm of two minds about the stderr/stdout debate; all I have is a nebulous feeling that the error about being outdated should be a warning instead, should be shorter (the first two lines could be combined into something like "You're using x.x.x, but the latest stable release is x.x.x"), and shouldn't break `entry2json`. In any case, if the error/warning could be suppressed for `convert entry2json` that'd sidestep that particular issue.

**Comment by garyluu** [comment]
Related:
There was an issue in the past where an enduser was running an old version of the Dockstore CLI and did not want to upgrade. The stderr (it used to be stderr) said to upgrade the Dockstore CLI and this was causing issues for them in determining whether their dockstore launch command has passed or failed.

**Comment by chmreid** [comment]
The behavior [as described](https://github.com/dockstore/dockstore/issues/3426), "it was put into stdout because some users didn't want to upgrade and also didn't want to see it the stderr when they run their workflows," sounds like an anti-pattern. Any errors and warnings should go to stderr, and anything parseable should go to stdout. That way, when a user runs a command like the [one in the comment just above that](https://github.com/dockstore/dockstore/issues/3426#issuecomment-623592851), it still produces valid JSON.

Warning messages should not break scripts, and this approach seems like it could unexpectedly break scripts that were producing valid JSON prior to a new release. If users don't want warning messages showing up in their stderr stream, we should not send warnings to stdout instead, we should provide some additional documentation/examples to users of how to use shell redirects to handle stdout/stderr.

**Comment by amarjandu** [comment]
Related to this issue, the `ds-cli` is generating invalid cwl files when trying to download from `quay.io`. 

```
dockstore tool cwl --entry quay.io/collaboratory/dockstore-tool-bamstats:1.25-7
Current version : 1.12.0
You have the most recent stable release.
If you wish to upgrade to the latest unstable version, please use the following command:
   dockstore --upgrade-unstable
#!/usr/bin/env cwl-runner

class: CommandLineTool
id: "BAMStats"
label: "BAMStats tool"
cwlVersion: v1.0
doc: |
    ![build_status](https://quay.io/repository/collaboratory/dockstore-tool-bamstats/status)
    A Docker container for the BAMStats command. See the [BAMStats](http://bamstats.sourceforge.net/) website for more information.

dct:creator:
  "@id": "http://orcid.org/0000-0002-7681-6415"
  foaf:name: Brian O'Connor
  foaf:mbox: "mailto:briandoconnor@gmail.com"

requirements:
  - class: DockerRequirement
    dockerPull: "quay.io/collaboratory/dockstore-tool-bamstats:1.25-6_1.0"

hints:
  - class: ResourceRequirement
    coresMin: 1
    ramMin: 4092  # "the process requires at least 4G of RAM"
    outdirMin: 512000

inputs:
  mem_gb:
    type: int
    default: 4
    doc: "The memory, in GB, for the reporting tool"
    inputBinding:
      position: 1

  bam_input:
    type: File
    doc: "The BAM file used as input, it must be sorted."
    format: "http://edamontology.org/format_2572"
    inputBinding:
      position: 2

outputs:
  bamstats_report:
    type: File
    format: "http://edamontology.org/format_3615"
    outputBinding:
      glob: bamstats_report.zip
    doc: "A zip file that contains the HTML report and various graphics."

baseCommand: ["bash", "/usr/local/bin/bamstats"]

$namespaces:
  dct: http://purl.org/dc/terms/
  foaf: http://xmlns.com/foaf/0.1/
```

In the tutorial the user is guided to create a file using the command
`dockstore tool cwl --entry quay.io/collaboratory/dockstore-tool-bamstats:1.25-7 > Dockstore.cwl`
`dockstore tool convert cwl2json --cwl Dockstore.cwl > Dockstore.json`

In both cases the files that are generated become malformed.

> `Any errors and warnings should go to stderr, and anything parseable should go to stdout.`

👍🏽
