### ISSUE TITLE
Declaratively define which collections a workflow belongs in

### ISSUE THREAD

**Issue by hexylena** [dockstore/dockstore#4472]
**Is your feature request related to a problem? Please describe.**
At the reminder of one of the outreach team, we're starting to think about pushing all of our workflows to Dockstore (~150 galaxy workflows), and the main blocker for us doing that is having to manually add them to our collections.

**Describe the solution you'd like**
I'd love to be able to declare which collections a workflow belongs in to help us scale things a bit better and ensure we don't accidentally forget to add workflows to their collections and give them the visibility we'd like. I recognise there's probably a data modelling issue from y'all's side where the relationship is the opposite, and collections point at workflows, rather than workflows pointing at collections, but, it'd still make my life easier for sure.

Maybe in a workflow that would look like:

```yaml
# Register workflows for Dockstore (https://dockstore.org/)
version: 1.2
workflows:
  - name: intro-short
    subclass: GALAXY
    primaryDescriptorPath: topics/introduction/tutorials/galaxy-intro-short/workflows/Galaxy-Workflow-galaxy-intro-short.ga
    collections:
      - gtn/trainingmaterial
      - gtn/introduction
  - name: gene-calling
    subclass: GALAXY
    primaryDescriptorPath: topics/genome-annotation/tutorials/gene-calling/workflows/main.ga
    collections:
      - gtn/trainingmaterial
      - gtn/genomeannotation
```

it feels 'weird' from the side of an organisation owner that I can write some yaml which results in a workflow created under my organisation, but I can't say "please place it in my own org's collections"

**Describe alternatives you've considered**
I've considered scripting this with the API, but the outreach member suggested filing this feature request, and if it's judged out of scope we'll probably end up writing something.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1916)
┆Fix Versions: Open-ended research tasks
┆Issue Number: DOCK-1916
┆Sprint: Backlog
┆Issue Type: Story
