### ISSUE TITLE
CLI fails to run CWL workflow with embedded CWL tool

### ISSUE THREAD

**Issue by wshands** [dockstore/dockstore#4616]
**Describe the bug**
When trying to use the Dockstore CLI to run a local CWL workflow that contains an embedded CWL tool the CLI fails, however cwltool will run the workflow.

**To Reproduce**
Run the workflow by executing the following command line:
`dockstore workflow launch --local-entry cwl_tool_wrapper_workflow.cwl --yaml cwl_tool_wrapper_workflow.yml `

You will see an error message like:

> Current version : 1.11.0
You have the most recent stable release.
If you wish to upgrade to the latest unstable version, please use the following command:
   dockstore --upgrade-unstable
[##################################################] 100%
Created temporary working directory at '/var/folders/vj/xky2f9pn64q6__y6w2kpjx4m0000gn/T/1638924727296-0'
Using local file 'cwl_tool_wrapper_workflow.cwl' as primary descriptor
Creating directories for run of Dockstore launcher at: /Users/waltershands/Documents/UCSC/gitroot/cwl-tool-wrapper-workflow/datastore//launcher-e9b67469-f9d6-4922-b50e-d061687a3c49
Provisioning your input files to your local machine
Parsed {baseCommand=[python, myscript.py], class=CommandLineTool, hints=[{class=DockerRequirement, dockerPull=quay.io/ucsc_cgl/simple_python:latest}, {class=InitialWorkDirRequirement, listing=[{entry=print("$(inputs.message)"), entryname=myscript.py}]}], inputs=[{id=file:///Users/waltershands/Documents/UCSC/gitroot/cwl-tool-wrapper-workflow/cwl_tool_wrapper_workflow.cwl#cwl_tool_wrapper_workflow_step/run/message, inputBinding={position=1.0}, type=string}], outputs=[]}
problems running command: cwltool --non-strict --print-pre {baseCommand=[python, myscript.py], class=CommandLineTool, hints=[{class=DockerRequirement, dockerPull=quay.io/ucsc_cgl/simple_python:latest}, {class=InitialWorkDirRequirement, listing=[{entry=print("$(inputs.message)"), entryname=myscript.py}]}], inputs=[{id=file:///Users/waltershands/Documents/UCSC/gitroot/cwl-tool-wrapper-workflow/cwl_tool_wrapper_workflow.cwl#cwl_tool_wrapper_workflow_step/run/message, inputBinding={position=1.0}, type=string}], outputs=[]}
stderr for command:
	INFO /Users/waltershands/.pyenv/versions/3.9.6/bin/cwltool 3.0.20200807132242
	Traceback (most recent call last):
	  File "/Users/waltershands/.pyenv/versions/3.9.6/bin/cwltool", line 8, in <module>
	    sys.exit(run())
	  File "/Users/waltershands/.pyenv/versions/3.9.6/lib/python3.9/site-packages/cwltool/main.py", line 1267, in run
	    sys.exit(main(*args, **kwargs))
	  File "/Users/waltershands/.pyenv/versions/3.9.6/lib/python3.9/site-packages/cwltool/main.py", line 905, in main
	    uri, tool_file_uri = resolve_tool_uri(
	  File "/Users/waltershands/.pyenv/versions/3.9.6/lib/python3.9/site-packages/cwltool/load_tool.py", line 100, in resolve_tool_uri
	    raise ValidationException("Not found: '%s'" % argsworkflow)
	schema_salad.exceptions.ValidationException: Not found: '{baseCommand=[python,'
	
CWL:
```
 #!/usr/bin/env cwl-runner

cwlVersion: v1.2
class: Workflow

# To wrap the CWL tool in a workflow you will still need to specify the inputs and outputs
inputs:
   # Specify the inputs to the CWL workflow here
   # The format will be more abreviated than the CWL tool inputs
   # Take a look at the user guide for more information:
   # https://www.commonwl.org/user_guide/21-1st-workflow/index.html
   message: string

outputs:
   # Specify the outputs from the CWL workflow here
   # The format will be more abreviated than the CWL tool outputs
   # Take a look at the user guide for more information:
   # https://www.commonwl.org/user_guide/21-1st-workflow/index.html
   []

steps:
  cwl_tool_wrapper_workflow_step:
    in:
       # Specify the inputs to the CWL tool here
       message: message
    out:
       # Specify the outputs from the CWL tool here
       []
    run:
      # Specify the descriptor for the CWL tool below by choosing the appropriate embedding method
      #
      # If the CWL tool is already registered in Dockstore you can simply embed a TRS URL
      # (This might not work if the execution engine does not support http(s) import statements)
      # The TRS URL can be found on the Dockstore public page for the tool
      # $import: https://dockstore.org/api/ga4gh/trs/v2/tools/quay.io%2Fucsc_cgl%2Fsimple_python/versions/develop/plain-CWL/descriptor//cwl_message_tool/cwl_message_tool.cwl
      #
      # OR
      #
      # Use the name of the CWL file that contains the tool description
      # (This might not work if there are dependencies in the tool CWL that cannot be resolved)
      # ./cwl_message_tool/cwl_message_tool.cwl
      #
      ## OR
      #
      # A URL to the repository location of the tool CWL
      # (This might not work if the execution engine does not support http(s) import statements or
      # there are dependencies in the tool CWL that cannot be resolved)
      # $import: https://raw.githubusercontent.com/DataBiosphere/cwl-tool-wrapper-workflow/develop/cwl_message_tool/cwl_message_tool.cwl
      #
      # OR
      #
      ## Embed the entire CWL tool specification as done in the example below
      #
       class: CommandLineTool
       hints:
         DockerRequirement:
           dockerPull: quay.io/ucsc_cgl/simple_python:latest

         InitialWorkDirRequirement:
           listing:
             - entryname: myscript.py
               entry: |-
                 print("$(inputs.message)")

       baseCommand:  ["python", "myscript.py"]
       inputs:
         message:
           type: string
           inputBinding:
             position: 1
       outputs: []
```
YML:
```
message: Hello world!
```
**Expected behavior**
The workflow should run successfully as it does using this command:
`cwltool cwl_tool_wrapper_workflow.cwl  cwl_tool_wrapper_workflow.yml`

**Screenshots**

![Screen Shot 2021-12-07 at 4 53 29 PM](https://user-images.githubusercontent.com/3650921/145129208-7a4897ba-a337-4b37-ab9a-cf5a365abbd0.png)

![Screen Shot 2021-12-07 at 5 02 08 PM](https://user-images.githubusercontent.com/3650921/145129820-86a238f4-40ba-4dd5-8246-5471a3c5b445.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 
CLI version 1.11.0
