### ISSUE TITLE
Support checker workflows in .dockstore.yml

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4654]
**Is your feature request related to a problem? Please describe.**
https://github.com/DataBiosphere/analysis_pipeline_WDL has multiple workflows which are beautifully handled by a .dockstore.yml (seriously, it makes testing new commits with Terra so much easier, y'all are rockstars), and I can add more workflows and test JSONs easily. 

Unfortunately I have to add checker workflows, which I wrote for all of my pipelines, manually. In theory I could create an entry for them in the .dockstore.yml but there seems to be no automated way to connect them as checker workflows.

**Describe the solution you'd like**
Optional syntax in a .dockstore.yml that allow for connecting a checker workflow to a workflow, ie:
```
version: 1.3
workflows:
   - subclass: WDL
     primaryDescriptorPath: /vcf-to-gds/vcf-to-gds.wdl
     testParameterFiles:
         - /vcf-to-gds/vcf-to-gds-terra.json
         - /vcf-to-gds/vcf-to-gds-local.json
      primaryCheckerPath: /vcf-to-gds/checker/vcf-to-gds-checker.wdl
      checkerParameterFiles:
         - /vcf-to-gds/checker/check-autosomes.json
         - /vcf-to-gds/checker/check-all-chrs.json
```
As-is, our checker entries still assume a primary descriptor, so only allowing one makes sense. But I like to use multiple configurations, so I'd like checker parameter files to have an arbitrary number of entries like we already do testParameterFiles.

**Describe alternatives you've considered**
Automatic checker workflow detection based on a defined file structure? Would probably be a bit of a pain to develop, and a pain for users to set up correctly.
