### ISSUE TITLE
GitHub Apps fails to sync multiple descriptors referenced by relative paths.

### ISSUE THREAD

**Issue by Richard-Hansen** [dockstore/dockstore#4715]
**Describe the bug**
(Took a look around and couldn't find a duplicate, but this may have been mentioned previously at some point?)

When syncing using a `.dockstore.yml` file, if you have a single workflow and are referencing the primary descriptor file using a relative path (relative to the repo root), this will succeed. If you add a second workflow, relative paths will fail on the GitHub Apps push with no error.

For example:

This will work (note the relative paths to the primary descriptor):
```
version: 1.2
workflows:

   -  name: single-descriptor-with-input
      subclass: WDL
      primaryDescriptorPath: workflows/wdl/w1/singleDescriptorWithInput.wdl
      testParameterFiles:
        - /workflows/wdl/w1/test.json
```

This will fail (note the relative paths to each primary descriptor):
```
version: 1.2
workflows:

   -  name: single-descriptor-with-input
      subclass: WDL
      primaryDescriptorPath: workflows/wdl/w1/singleDescriptorWithInput.wdl
      testParameterFiles:
        - /workflows/wdl/w1/test.json
        
   -  name: multi-descriptor-no-input
      subclass: WDL
      primaryDescriptorPath: workflows/wdl/w2/multiDescriptorNoInput.wdl
```

This will work (note the absolute paths to each primary descriptor):
```
version: 1.2
workflows:

   -  name: single-descriptor-with-input
      subclass: WDL
      primaryDescriptorPath: /workflows/wdl/w1/singleDescriptorWithInput.wdl
      testParameterFiles:
        - /workflows/wdl/w1/test.json
        
   -  name: multi-descriptor-no-input
      subclass: WDL
      primaryDescriptorPath: /workflows/wdl/w2/multiDescriptorNoInput.wdl
```

**To Reproduce**
1. Attempt a GitHub Apps sync using each of the 3 `.dockstore.yml` files shown above. At the time of writing this issue, the workflows are stored in https://github.com/dockstore-testing/wes-testing

**Expected behavior**
If we don't want any relative paths, that should give a detailed error and have a failed GitHub Apps event, so the first two cases above should fail. If we do want to allow relative paths, every case above should work.

**Screenshot of a failed event with no logs**
![Screen Shot 2022-02-08 at 5 20 47 PM](https://user-images.githubusercontent.com/36607471/153085390-0186c470-7b33-4249-a7c6-9edeb5f61a60.png)

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.11.10) - 1.11.10

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.8.4) - 2.8.4

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.11.1) - 1.11.1

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.11.2) - 1.11.2

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2058)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-2058
┆sprint: 94- Vampire Pleco
┆taskType: Story
