### ISSUE TITLE
Improve .dockstore.yml validation in DockstoreYamlHelper

### ISSUE THREAD

**Issue by fhembroff** [dockstore/dockstore#4985]
**Is your feature request related to a problem? Please describe.**
Currently it is possible for invalid `.dockstore.yml` files (according to the rules specified [here](https://docs.dockstore.org/en/stable/assets/templates/template.html)) to pass through the functions `DockstoreYaml.readAndValidateDockstoreYaml` and  `DockstoreYaml.validateDockstoreYamlProperties` without error.

**Describe the solution you'd like**
I would like for only valid `.dockstore.yml` files to pass through the above functions.

**Additional context**
This problem was discovered in this [PR](https://github.com/dockstore/dockstore-cli/pull/161).

Some examples of incorrect files that will pass are,
```
version: 1.2
tools:
  - subclass: CWL
    primaryDescriptorPath: /runGlobalAligner.cwl
    testParameterFiles:
      - /test/globalAligner.cwl.json
    authors:
      - name: Bob Generic Example
        email: makesuretofilloutanactualemailaddress@ucsc.edu
  - subclass: CWL
    primaryDescriptorPath: /runLocalAligner.cwl
    testParameterFiles:
      - /test/localAligner.cwl.json
    authors:
      - orcid: 0000-0000-0000-0000
      - orcid: 1111-1111-1111-1111
      - name: Bob Generic Example Jr
        email: anotherpersonsemailaddress@ucsc.edu
        
```
This should have failed as it has two tools without names being specified.
```
version: 1.2

tools:
  - subclass: WDL
    primaryDescriptorPath: /runGlobalAligner.cwl
    testParameterFiles:
      - /test/globalAligner.cwl.json
    authors:
      - name: Bob Generic Example
        email: makesuretofilloutanactualemailaddress@ucsc.edu
```
This should have failed as `.dockstore.yml registration does not support WDL tools`.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2194)
┆Attachments: <a href="https://ucsc-cgl.atlassian.net/rest/api/2/attachment/content/10877">image-20221201-210505.png</a> | <a href="https://ucsc-cgl.atlassian.net/rest/api/2/attachment/content/10878">image-20221201-210537.png</a>
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2194
┆Sprint: 95- W
┆Issue Type: Story

**Comment by fhembroff** [comment]
I don't know if this was intended but this [PR](https://github.com/dockstore/dockstore/pull/4843/files) made the error message of missing parameters a little confusing to non-technical users.

For example if you use the following yaml,
```
version: 1.2
workflows:
  -  name: test
     subclass: WDL
     authors:
       - name: Denis Yuen
         orcid: 0000-0002-6130-1021
       - name: UCSC Genomics Institute
         role: Institute
         affiliation: UCSC
     publish: true
     testParameterFiles:
       - /dockstore.wdl.json
       - /dockstore.cwl.json
       - /Dockstore.cwl
     filters:
       branches:
         - develop
       tags:
         - gwas*
```
You get this error message:
```
Property "workflows[0].primaryDescriptorPath" is missing but required
```
I think `workflows[0]` might confuse some people, so I think using the name of the workflow (if given) might be better, perhaps saying something like `Property primaryDescriptorPath is missing in workflow test`. If they had multiple workflows but didn't name them then I think it should first throw an error about the missing names and exit.
