### ISSUE TITLE
Dockstore-based workflows with registered tools

### ISSUE THREAD

**Issue by wdesouza** [dockstore/dockstore#770]
## Feature Request

Is it possible to create Workflow using Tools registered in Dockstore? I noticed that many available workflows in Dockstore provide all tools (CWL files) locally. I want to write Workflow files (CWL) using tools that I previously registered in Dockstore. Any ideia?

### Desired behaviour

A CWL Workflow example:

``` yml
# ...
steps:
  quality_report:
    run:  registry.hub.docker.com/welliton/rqc # latest version
    in: {}
    out: {}
  quality_control:
    run: registry.hub.docker.com/welliton/trimgalore:v0.4.4 # with tag
    in: {}
    out: {}
# ...
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-490)
┆fixVersions: Dockstore 2.X
┆friendlyId: DOCK-490
┆sprint: Backlog
┆taskType: Story

**Comment by denis-yuen** [comment]
Hi,
I think the approach that comes to mind to try is:
Multiple tools are built from multiple Dockerfiles+CWL files in one repo. These are then added to Dockstore
Subsequently, a workflow is added to the same repo that uses those tools. 

We haven't tried sharing multiple tools between multiple repos yet, however. It might depend on how to reference a CWL step in a different repo in CWL.

**Comment by keiranmraine** [comment]
This is something we'd also like to be able to do.  To some extent we're also thinking about 'custom' CWL which isn't in a repo but uses registered tools to allow experimentation or user centric plug-and-play.

**Comment by denis-yuen** [comment]
One thought I had is I have the impression you may be able to import workflow steps via URL http://www.commonwl.org/v1.0/SchemaSalad.html#Import

This is something that I haven't tried myself yet, but if it works, it might be nice to work out a pattern based on this and support it in Dockstore explicitly.

**Comment by Welliton309** [comment]
Thank you @denis-yuen for your suggestion. It worked! I used the URL for raw `Dockstore.cwl` file from GithHub. See example below.

``` yml
cwlVersion: v1.0
class: Workflow

inputs:
  files: File[]
  groups: string[]

outputs:
  qc_report:
    type: File
    outputSource: qc_raw/qc_report

steps:
  qc_raw:
    run: https://raw.githubusercontent.com/labbcb/dockstore-rqc/v3.5/Dockstore.cwl
    in:
      files: files
      groups: groups
    out: [qc_report]
```

Input example:

``` yml
files:
  - class: File
    path: ERR127302_1_subset.fastq.gz
  - class: File
    path: ERR127302_2_subset.fastq.gz
groups: [None, None]
```

I tested using `cwltool`. Another way is to dowload CWL files via `dockstore tool cwl`. For example:

``` bash
dockstore tool cwl --entry registry.hub.docker.com/welliton/rqc:v3.5 > Rqc.cwl
```
